services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: unless-stopped
        image: ghcr.io/thatdaveguy1/docker-wyze-bridge:latest
        network_mode: host
        #ports:
        #    - 8554:8554/tcp    # RTSP rtsp://localhost:8554/camera-name
        #    - 8888:8888/tcp    # HLS http://localhost:8888/camera-name/stream.m3u8
        #    - 8889:8889/tcp    # WebRTC http://localhost:8889/camera-name
        #    - 5000:5000/tcp    # Web UI http://localhost:5000
        environment:
            # [REQUIRED] Wyze credentials
            # API Key and ID can be obtained from the Wyze dev portal: 
            # https://developer-api-console.wyze.com/#/apikey/view
            - WYZE_EMAIL=
            - WYZE_PASSWORD= 
            - API_ID=
            - API_KEY= 
            # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
            # - WB_IP=192.168.1.122
            # WebUI and Stream authentication:
            # - WB_AUTH=True
            # - WB_USERNAME=admin
            # - WB_PASSWORD=password
