mqtt:
  host: <HA_HOST>
  user: mqtt
  password: <MQTT_PASSWORD>

ffmpeg:
  hwaccel_args: preset-vaapi
  retry_interval: 10

detectors:
  ov:
    type: openvino
    device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

record:
  enabled: true
  alerts:
    retain:
      days: 15
  detections:
    retain:
      days: 15
  continuous:
    days: 3
  motion:
    days: 3

snapshots:
  enabled: true
  retain:
    default: 15

objects:
  track:
    - person
    - car
    - dog
    - bicycle
  filters:
    person:
      min_score: 0.1
      threshold: 0.2
    car:
      min_score: 0.2
      threshold: 0.3

detect:
  enabled: true

birdseye:
  enabled: true

go2rtc:
  streams:
    cam_driveway:
      - rtsp://admin:REDACTED@<CAMERA_IP>:554/h264Preview_01_sub
    cam_driveway_ptz:
      - rtsp://admin:REDACTED@<CAMERA_IP>:554/h264Preview_02_sub
    cam_patio-sd:
      - rtsp://<HA_HOST>:8554/cam_patio-sd
    cam_side_yard-sd:
      - rtsp://<HA_HOST>:8554/cam_side_yard-sd
    cam_back_yard-sd:
      - rtsp://<HA_HOST>:8554/cam_back_yard-sd
    cam_garage-sd:
      - rtsp://<HA_HOST>:8554/cam_garage-sd
    cam_side_gate-sd:
      - rtsp://<HA_HOST>:8554/cam_side_gate-sd

cameras:
  cam_front_door:
    ffmpeg:
      inputs:
        - path: rtsp://admin:REDACTED@<CAMERA_IP>:554/h264Preview_01_sub
          input_args: -rtsp_transport tcp -an
          roles:
            - record
            - detect
    detect:
      width: 640
      height: 480
      fps: 5
    snapshots:
      enabled: true
      bounding_box: false
      timestamp: true
      crop: true
    record:
      enabled: true
    motion:
      enabled: true
      threshold: 20
      contour_area: 10
      improve_contrast: false
      mask:
        - 0.357,0.419,0.622,0.422,0.624,0.519,0.705,0.519,0.69,0.179,0.376,0.141
    objects:
      filters:
        car:
          mask: 0.997,0.999,0.006,0.999,0.004,0.011,0.992,0.016
        person:
          mask:
            - 0.435,0.657,0.429,0.585,0.458,0.585,0.466,0.616,0.466,0.655
            - 0.474,0.688,0.474,0.63,0.491,0.611,0.517,0.611,0.526,0.63,0.526,0.652,0.529,0.682,0.509,0.698

  cam_driveway:
    best_image_timeout: 60
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_driveway
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 1920
      height: 720
      fps: 5
    snapshots:
      enabled: true
      bounding_box: false
      timestamp: true
      crop: true
    record:
      enabled: true
    motion:
      enabled: true
      threshold: 25
      contour_area: 10
      improve_contrast: false

  cam_driveway_ptz:
    best_image_timeout: 60
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_driveway_ptz
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      width: 896
      height: 512
      fps: 5
    snapshots:
      enabled: true
      bounding_box: false
      timestamp: true
      crop: true
    record:
      enabled: true
    motion:
      enabled: true
      threshold: 25
      contour_area: 10
      improve_contrast: false

  cam_patio:
    best_image_timeout: 60
    ffmpeg:
      inputs:
        - path: rtsp://<HA_HOST>:8554/cam_patio-sd
          input_args: -rtsp_transport tcp -an -analyzeduration 5000000 -probesize 5000000
          roles:
            - detect
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    snapshots:
      enabled: true
      bounding_box: false
      timestamp: true
      crop: true
    record:
      enabled: true
    objects:
      track:
        - person
        - dog
    motion:
      enabled: true
      threshold: 25
      contour_area: 10
      improve_contrast: false

  cam_side_yard:
    best_image_timeout: 60
    ffmpeg:
      inputs:
        - path: rtsp://<HA_HOST>:8554/cam_side_yard-sd
          input_args: -rtsp_transport tcp -an -analyzeduration 5000000 -probesize 5000000
          roles:
            - detect
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    snapshots:
      enabled: true
      bounding_box: false
      timestamp: true
      crop: true
    record:
      enabled: true
    objects:
      track:
        - person
        - dog
    motion:
      enabled: true
      threshold: 25
      contour_area: 10
      improve_contrast: false

  cam_back_yard:
    best_image_timeout: 60
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://<HA_HOST>:42455/<SCRYPTED_STREAM_HASH>
          input_args: -rtsp_transport tcp -an
          roles:
            - detect
        - path: rtsp://<HA_HOST>:42455/<SCRYPTED_STREAM_HASH>
          input_args: -rtsp_transport tcp -an
          roles:
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    snapshots:
      enabled: true
      bounding_box: false
      timestamp: true
      crop: true
    record:
      enabled: true
    motion:
      enabled: true
      threshold: 25
      contour_area: 10
      improve_contrast: false

  cam_side_gate:
    best_image_timeout: 60
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://<HA_HOST>:8554/cam_side_gate-sd
          input_args: -rtsp_transport tcp -an -fflags nobuffer -analyzeduration 10000000 -probesize 10000000
          roles:
            - detect
            - record
    detect:
      width: 1296
      height: 1728
      fps: 5
    snapshots:
      enabled: true
      bounding_box: false
      timestamp: true
      crop: true
    record:
      enabled: true
    motion:
      enabled: true
      threshold: 25
      contour_area: 10
      improve_contrast: false

  cam_garage:
    best_image_timeout: 60
    ffmpeg:
      hwaccel_args: ''
      inputs:
        - path: rtsp://<HA_HOST>:8554/cam_garage-sd
          input_args: -rtsp_transport tcp -an -fflags nobuffer -analyzeduration 10000000 -probesize 10000000
          roles:
            - detect
            - record
    detect:
      width: 640
      height: 360
      fps: 5
    snapshots:
      enabled: true
      bounding_box: false
      timestamp: true
      crop: true
    record:
      enabled: true
    objects:
      track:
        - person
    motion:
      enabled: true
      threshold: 25
      contour_area: 10
      improve_contrast: false

version: 0.17-0

camera_groups:
  Front:
    order: 1
    icon: LuAirplay
    cameras:
      - cam_front_door
      - cam_driveway
      - cam_driveway_ptz
  Yard:
    order: 2
    icon: LuTrees
    cameras:
      - cam_patio
      - cam_side_yard
      - cam_back_yard
      - cam_garage
      - cam_side_gate
